create table if not exists trading_audit_pause_governance_events (
    sequence_number bigint generated by default as identity primary key,
    event_type varchar(128),
    provider varchar(64) not null,
    environment varchar(64) not null,
    account varchar(128) not null,
    market varchar(128) not null,
    symbol varchar(128),
    pause_scope varchar(64),
    pause_target varchar(256),
    remediation_id varchar(512),
    event_id varchar(512),
    source_pause_remediation_id varchar(512),
    command_id varchar(512),
    client_order_id varchar(512),
    decision_id varchar(512),
    risk_decision varchar(64),
    outcome varchar(128),
    actor varchar(256),
    reason varchar(2048),
    expires_at varchar(64),
    invalid_reason varchar(2048),
    occurred_at varchar(64),
    payload text not null
);

create index if not exists trading_audit_pause_governance_scope_idx
    on trading_audit_pause_governance_events (provider, environment, account, market, occurred_at, sequence_number);

create index if not exists trading_audit_pause_governance_event_id_idx
    on trading_audit_pause_governance_events (event_id);

create index if not exists trading_audit_pause_governance_remediation_id_idx
    on trading_audit_pause_governance_events (remediation_id);

create index if not exists trading_audit_pause_governance_pause_target_idx
    on trading_audit_pause_governance_events (provider, environment, account, market, pause_scope, pause_target);
